version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres_fipe
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fipe_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/import.sql:/docker-entrypoint-initdb.d/import.sql

  redis:
    image: redis:7
    container_name: redis_fipe
    restart: always
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbit_fipe
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: fipe_user
      RABBITMQ_DEFAULT_PASS: fipe_pass
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres_data: